name: Flutter CI

# 언제 실행할지 정의
on:
  # main 브랜치에 push 시 실행
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-test:
    name: 분석
    runs-on: ubuntu-latest

    steps:
      - name: 체크아웃
        uses: actions/checkout@v6

      - name: 플러터 환경 세팅
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.5"
          channel: "stable"
          cache: true

      - name: 의존성 설치
        run: flutter pub get

      - name: 코드 분석
        run: flutter analyze --fatal-infos

      - name: 코드 포맷팅
        run: dart format --output=none --set-exit-if-changed .
